# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolf_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='name',
            field=models.CharField(default=b'prod', max_length=256),
        ),
    ]
